### ISSUE TITLE
no compile

### ISSUE THREAD

**Issue by SorenGullach** [riverdi/riverdi-70-stm32h7-lvgl#1]
It do not compile!
lvgl/lvgl.h is missing

**Comment by lukasz-skalski** [comment]
Hi @SorenGullach,

Did you download repository using 'git' command with '--recursive' flag?

**Comment by SorenGullach** [comment]
Nice it works now
Now we just need to make a VisualGDB version, to rid of this sily CubeIDE
and next without CubeMX :-)
